#pragma once
//
//#include "BEUtilityPlatformDefines.h"
//#include "BEUtilityPlatformTypes.h"
//#include "BEUtilityMacro.h"
//#include "BEStdHeaders.h"
//
//#include "BELogger.h"
//#include "BEMath.h"
//#include "Degree.h"
//#include "Radian.h"
//#include "Vector2D.h"
//#include "Vector2DI.h"
//#include "Vector3D.h"
//#include "Vector4D.h"
//#include "Matrix3D.h"
//#include "Matrix4D.h"
//#include "Rect2D.h"
//#include "Rect2DI.h"
//#include "Rect3D.h"